//
//  StringConstants.swift
//  LoginSignUp
//
//  Created by Aamir khan on 09/05/23.
//

import Foundation

//MARK: Contains all strings used in project.
enum StringConstants : String{
    case noName = "No Name",
    emptyString = "",
    defaultValue = "default",
    placeHolder = "PlaceHolder",
    imageForAllViews = "LoginSignImage2",
    noValue = "No Value",
    submit  = "Submit",
    email = "Email",
    placeHolderForEmail = "Your email id",
    forgotPassword = "Forgot password",
    backToLogin = "Back to login",
    SignUp = "Sign-up",
    defaultCamera = "defaultCameraImage",
    photo = "photo",
    selectPhoto = "Select your profile photo",
    namePlaceholder = "Your Name",
    name = "Name",
    contactNumber = "Your Contact number",
    contactNo = "Contact no.",
    password = "Password",
    confirmPassword = "Confirm Password",
    noNumber = "No number",
    noEmail = "No email",
    noPassword = "No password",
    signUpTwo = "Sign up",
    thankYou = "ThankYouImage",
    congratsMsg = "Congratulation, You Signed up succesfully!",
    goToLogin = "Go back to Login Page",
    Login = "Log-in",
    enterMailId = "Please Enter your email id",
    loginTwo = "Login",
    dontHaveAccount = "Don't have an account ?",
    orLoginWith = "Or login with",
    facebookImage = "facebookCircular",
    gmailImage = "gmailCircular",
    yourDetails = "Your Details",
    selfMatches = "SELF MATCHES %@",
    nameRegex = "^[\\p{L} .'-]+$",
    passwordRegex = "^(?=.*\\d).{4,8}$",
    emailRegex = "^\\w+@[a-zA-Z_]+?\\.[a-zA-Z]{2,3}$",
    numberRegex = "^(\\+91[\\-\\s]?)?[0]?(91)?[789]\\d{9}$",
    enterValidPassword = "Enter a valid password.",
    passwordMatch = "Passwords Should match.",
    enterValidMail = "Enter a valid Email ID.",
    enterValidContact = "Enter a valid Contact Number.",
    enterValidName = "Enter a valid Name.",
    urlToSaveData = "https://jsonplaceholder.typicode.com/todos",
    invalidURL = "Not a valid URL",
    post = "POST",
    unableToDecode = "unable To encode data",
    typeOfDataToBeSaved = "application/json",
    contectType = "Content-Type",
    dataNotFound = "Data Not Found",
    imageUrlForDetailView = "https://img.freepik.com/free-photo/young-bearded-man-with-striped-shirt_273609-5677.jpg?w=740&t=st=1683610457~exp=1683611057~hmac=3a7db3be3d4399b71fa4fe8788f40084b79a040f8f7f747b0b5d4502a43dbcdd",
    eyeSlash = "eye.slash",
    eye = "eye",
    isRoot = "isRoot",
    userName = "Aamir",
    userNumber = "9899356475",
    userID = "aamir@gmail.com",
    userPassword = "Abc123"
}
